"""
FuzzPhantom — HackerOne Report Format
Generates a Markdown report formatted for HackerOne bug bounty submissions.
"""

from __future__ import annotations

from datetime import datetime
from pathlib import Path

from core.context import ScanContext, Finding
from core.logger import get_logger

logger = get_logger(__name__)

SEVERITY_MAP = {
    "CRITICAL": "critical",
    "HIGH": "high",
    "MEDIUM": "medium",
    "LOW": "low",
    "INFO": "informational",
}


def _format_finding(finding: Finding, index: int) -> str:
    severity_h1 = SEVERITY_MAP.get(finding.severity.upper(), "informational")

    evidence_block = ""
    if finding.evidence:
        evidence_block = f"""
### Response Evidence
```
{finding.evidence[:600]}
```
"""

    payload_block = ""
    if finding.payload:
        payload_block = f"""
### Payload Used
```
{finding.payload}
```
"""

    return f"""---

## Finding #{index}: {finding.category}

| Field | Value |
|---|---|
| **Severity** | {severity_h1.upper()} |
| **URL** | `{finding.url}` |
| **Parameter** | `{finding.parameter or "N/A"}` |
| **Status Code** | `{finding.status_code}` (was `{finding.original_status}`) |
| **Response Length** | `{finding.response_length}` bytes (was `{finding.original_length}`) |

### Description
{finding.detail}
{payload_block}{evidence_block}
### Steps to Reproduce
1. Navigate to: `{finding.url}`
2. Inject payload into parameter `{finding.parameter or "N/A"}`: `{finding.payload or "N/A"}`
3. Observe: {finding.detail}

### Impact
This finding may allow an attacker to exploit `{finding.category}` on `{finding.url}`.

### Remediation
Implement strict input validation and output encoding. Review server configuration
to ensure verbose errors are not exposed in production environments.

"""


def export_hackerone(ctx: ScanContext, output_dir: str) -> str:
    """Generate a HackerOne-formatted Markdown report."""
    out_dir = Path(output_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    filename = out_dir / f"hackerone_{ctx.target_domain}_{timestamp}.md"

    summary = ctx.summary()
    findings_md = "\n".join(
        _format_finding(f, i + 1)
        for i, f in enumerate(ctx.findings)
    )

    report = f"""# FuzzPhantom Security Assessment Report
## Platform: HackerOne

> **Generated by:** FuzzPhantom v1.0.0
> **Target:** `{ctx.target_domain}`
> **Date:** {datetime.now().strftime("%Y-%m-%d %H:%M UTC")}

---

## Executive Summary

| Metric | Count |
|---|---|
| Subdomains Discovered | {summary["subdomains"]} |
| URLs Crawled | {summary["crawled_urls"]} |
| Parameterized URLs | {summary["parameterized_urls"]} |
| API Endpoints Found | {summary["api_endpoints"]} |
| JavaScript Files | {summary["js_files"]} |
| **Total Findings** | **{summary["findings"]}** |

### Severity Breakdown

| Severity | Count |
|---|---|
| 🔴 Critical | {sum(1 for f in ctx.findings if f.severity == "CRITICAL")} |
| 🟠 High | {sum(1 for f in ctx.findings if f.severity == "HIGH")} |
| 🟡 Medium | {sum(1 for f in ctx.findings if f.severity == "MEDIUM")} |
| 🟢 Low | {sum(1 for f in ctx.findings if f.severity == "LOW")} |
| ℹ️ Info | {sum(1 for f in ctx.findings if f.severity == "INFO")} |

---

## Discovered Subdomains

```
{chr(10).join(ctx.subdomains) or "None"}
```

## API Endpoints

```
{chr(10).join(ctx.api_endpoints) or "None"}
```

---

## Findings

{findings_md if ctx.findings else "_No actionable findings discovered._"}

---

*This report was automatically generated by [FuzzPhantom](https://github.com/fuzzphantom).
Always verify findings manually before submission.*
"""

    with open(filename, "w", encoding="utf-8") as fp:
        fp.write(report)

    logger.info(f"HackerOne report saved: [cyan]{filename}[/cyan]")
    return str(filename)
